# Site Settings
baseurl: ""
url : "https://ptrckstuns.github.io"
# url: "https://patrickcastro.xyz"

# Blog Settings
theme_settings :
  title : ptrckstuns
  favicon : assets/img/fox.png

  # Profile Settings
  profile :
    image : assets/img/rei.jpg
    username : Patrick Castro
    description : Penetration Tester, Red Teamer
    experience :
      - start : 2023-10-16
        end : Present
        experience : Manulife, Junior Penetration Tester
      - start : 2022-08-01
        end : 2023-10-09
        experience : KPMG Philippines, Consultant I
      - start : 2022-02-28
        end : 2022-05-17
        experience : Poseidon IT Solutions, Security Analyst Intern
    skills : 
      - skill : Vulnerability Assessment & Penetration Testing (Web, Network, API) 
      - skill : Red Teaming (Phishing, Physical Security, Wireless Testing)
      - skill : Application Security
      - skill : Backend - Python & Django & Flask
      - skill : Web Development - HTML & CSS & JS        
      - skill : C, C++, C#, Java, PHP
      - skill : SQL
        value : 75  # Percent value
    certifications :
      - cert: eWPT - eLearnSecurity Web application Penetration Tester
      - cert: Certified AppSec Pentester (CAPen)
      - cert: Certified AppSec Practitioner (CAP) 
      - cert : eJPT - eLearnSecurity Junior Penetration Tester 
      - cert : C)PTE - Mile2 Certified Penetration Testing Engineer
      - cert : (ISC)2 CC - Certified in Cybersecurity
      - cert : C)SA1 - Mile2 Certified Security Awareness 1
 
        
  # Icons
  icons :
    email: pm.andreicastro@gmail.com 
    proton: ptrckstuns@proton.me # Full email address, e.g. "sample@google.com"
    linkedin: https://linkedin.com/in/ptrckstuns # Full URL 
    github: ptrckstuns
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: ptrckstuns0_0
    youtube: 
    facebook: 
    instagram: patrickcastro__
    twitch: ptrckstunsx

  # Disqus
  disqus_shortname : #ptrckstuns

# Pagination
paginate: 4
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
