# Site Settings
baseurl: ""
url : "https://ptrckstuns.github.io"
# url: "https://ptrckstuns.codes"

# Blog Settings
theme_settings :
  title : ptrckstuns
  favicon : assets/img/fox.png

  # Profile Settings
  profile :
    image : assets/img/rei.jpg
    username : Patrick Castro
    description : Cyber Security Consultant
    experience :
      - start : 2022-08-01
        end : Present
        experience : KPMG Philippines, Consultant I
      - start : 2022-02-28
        end : 2022-05-17
        experience : Poseidon IT Solutions, Security Analyst Intern
    skills : 
      - skill : Vulnerability Assessment & Penetration Testing
      - skill : Python & Django & Flask
      - skill : HTML & CSS & JS        
      - skill : C, C++, C#, Java, PHP
      - skill : MySQL, Microsoft SQL Server
        value : 75  # Percent value
    certifications:
      - cert : eJPT - eLearnSecurity Junior Penetration Tester 
      - cert : C)PTE - Certified Penetration Testing Engineer
      - cert : C)SA1 - Certified Security Awareness 1
        
  # Icons
  icons :
    email: pm.andreicastro@gmail.com 
    proton: ptrckstuns@proton.me # Full email address, e.g. "sample@google.com"
    linkedin: https://linkedin.com/in/ptrckstuns # Full URL 
    github: ptrckstuns
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: ptrckstuns0_0
    youtube: 
    facebook: 
    instagram: patrickcastro__

  # Disqus
  disqus_shortname : ptrckstuns

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
