# Site Settings
baseurl: ""
# url : "https://ptrckstuns.github.io"
url: "https://ptrckstuns.codes"

# Blog Settings
theme_settings :
  title : ptrckstuns
  favicon : assets/img/fox.png

  # Profile Settings
  profile :
    image : assets/img/rei.jpg
    username : Patrick Castro
    description : Cyber Security Consultant | Computer Science graduate | cybersecurity enthusiast
    experience :
      - start : 2022-02-28
        end : 2022-05-17
        experience : Poseidon IT Solutions, Security Analyst Intern
      - start : 2022-08-01
        end : Present
        experience : KPMG Philippines, Consultant I
    skills : 
      - skill : HTML & CSS & JS
        value : 85  # Percent value
      - skill : Python & Django & Flask
        value : 80  # Percent value
      - skill : C, C++, C#, Java, PHP
        value : 75  # Percent value
      - skill : MySQL, Microsoft SQL Server
      - skill : Vulnerability Scanning & Penetration Testing
    certifications:
      - cert : eLearnSecurity Junior Penetration Tester (eJPT)
        
  # Icons
  icons :
    email: patrick.castro.stuns@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin: https://linkedin.com/in/ptrckstuns # Full URL 
    github: ptrckstuns
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: _ptrckstuns_1
    youtube: 
    facebook: 
    instagram: 

  # Disqus
  disqus_shortname : ptrckstuns

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
